version: '3.8'

services:
  # Other services remain the same as in docker-compose.yml
  
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # We'll create this file next
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mount the frontend directory into the container
      - /app/node_modules  # Preserve node_modules from the container
    environment:
      - REACT_APP_API_URL=http://backend:4000/graphql
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Needed for hot reloading in some environments
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 